register tool versions with unique vars

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -13,7 +13,8 @@ deployctx(){
 	done
 
 	if [[ "$1" == "build" ]]; then
-		__deployctx_build || return 1
+		##TODO check argc
+		__deployctx_build $2 $3 || return 1
 		return 0
 	fi
 
@@ -21,52 +22,57 @@ deployctx(){
 	tool="$(printf "%s\n" ${tools[@]} | fzf)"
 	version="$(ls --hide=global* $DEPLOYCTX_PATH/$tool | fzf)"
 	alias $tool="__deployctx_$tool"
+	vartoload=DEPLOYCTX_${tool//-/_}_VERSION
+	export ${vartoload^^}=$version
 	echo "Switched to $tool/$version"
+	unset tool
+	unset version
+	unset vartoload
 }
 
 __deployctx_check_image(){
-	if [[ "$(docker images -q deployctx-$tool:$version 2> /dev/null)" == "" ]]; then
+	if [[ "$(docker images -q deployctx-$1:$2 2> /dev/null)" == "" ]]; then
 		echo "First build the image with deployctx build"
 		return 1
 	fi
 }
 
 __deployctx_build(){
-	if [[ -z "$tool" || -z "$version" ]]; then
-		echo "Nothing to build"
+	if [[ -z "$1" || -z "$2" ]]; then
+		echo "Name of the tool or its version is missing."
 		return 1
 	fi
 
-        docker build --network=host -t deployctx-$tool:$version -f $DEPLOYCTX_PATH/$tool/$version/Dockerfile .
+        docker build --network=host -t deployctx-$1:$2 -f $DEPLOYCTX_PATH/$1/$2/Dockerfile .
 }
 
 __deployctx_kolla-ansible(){
-	__deployctx_check_image || return 1
+	__deployctx_check_image kolla-ansible $DEPLOYCTX_KOLLA_ANSIBLE_VERSION || return 1
 
-	if [[ ! -f $DEPLOYCTX_PATH/config/$tool/$version ]]; then
-		mkdir -p $DEPLOYCTX_PATH/config/$tool/$version
+	if [[ ! -f $DEPLOYCTX_PATH/config/kolla-ansible/$DEPLOYCTX_KOLLA_ANSIBLE_VERSION ]]; then
+		mkdir -p $DEPLOYCTX_PATH/config/kolla-ansible/$DEPLOYCTX_KOLLA_ANSIBLE_VERSION
 	fi
 
 	docker run -it --rm --network=host  \
-		-v $DEPLOYCTX_PATH/config/$tool/$version/:/etc/kolla \
+		-v $DEPLOYCTX_PATH/config/kolla-ansible/$DEPLOYCTX_KOLLA_ANSIBLE_VERSION/:/etc/kolla \
 		-v $DEPLOYCTX_PATH/inventory:/app/inventory/inv \
 		-v ~/.ssh:/tmp/.ssh \
 		--dns 127.0.0.1 \
-		deployctx-$tool:$version \
+		deployctx-kolla-ansible:$DEPLOYCTX_KOLLA_ANSIBLE_VERSION \
 		kolla-ansible -i /app/inventory $@
 
 }
 
 __deployctx_ceph-ansible(){
-	__deployctx_check_image || return 1
+	__deployctx_check_image ceph-ansible $DEPLOYCTX_CEPH_ANSIBLE_VERSION || return 1
 
-	if [[ ! -f $DEPLOYCTX_PATH/config/$tool/$version ]]; then
-		mkdir -p $DEPLOYCTX_PATH/config/$tool/$version
+	if [[ ! -f $DEPLOYCTX_PATH/config/ceph-ansible/$DEPLOYCTX_CEPH_ANSIBLE_VERSION ]]; then
+		mkdir -p $DEPLOYCTX_PATH/config/ceph-ansible/$DEPLOYCTX_CEPH_ANSIBLE_VERSION
 	fi
 
 	docker run -it --rm --network=host  \
-		-v $DEPLOYCTX_PATH/config/$tool/$version/:/app/ceph-ansible/group_vars \
+		-v $DEPLOYCTX_PATH/config/ceph-ansible/$DEPLOYCTX_CEPH_ANSIBLE_VERSION/:/app/ceph-ansible/group_vars \
 		-v $DEPLOYCTX_PATH/inventory:/etc/ansible/inventory \
-		deployctx-$tool:$version \
+		deployctx-ceph-ansible:$DEPLOYCTX_CEPH_ANSIBLE_VERSION \
 	       	ansible-playbook -i /etc/ansible/inventory $@
 }
